### ISSUE TITLE
not showing favicons

### ISSUE THREAD

**Issue by mErchamion** [sciancio/searchfirefoxbookmarks#1]
Hi! I have just installed the extension. it works, but it does not show the favicons in the search results, not even the firefox icon. I will be thankfull if it is solved! greetings ...

**Comment by sciancio** [comment]
Hi,

which distro are you using?

**Comment by mErchamion** [comment]
I am using ubuntu oneiric (11.10) with gnome shell 3.2.1, firefox 10 as recently updated.Thank you for the quick response!

**Comment by AbhijithMadhav** [comment]
@mErchamion, I too had the same problem. I was using ubuntu-11.10 with gnome-shell 3.2.1. I have effected a change that fixes this for me. Can you see if https://github.com/AbhijithMadhav/searchfirefoxbookmarks solves your problem?

@sciancio, If it does I will issue a pull request.

**Comment by sciancio** [comment]
Hi AbhijithMadhav,

your change is ok for me too. I have applied the patch. Thanks.
