### ISSUE TITLE
Not working in Gnome-Shell 3.8

### ISSUE THREAD

**Issue by mightymouse2045** [sciancio/searchfirefoxbookmarks#6]
Any chance of getting this updated - it's very helpful!

**Comment by haraldkrischner** [comment]
I forked a 3.8 compatible version. Perhaps I should consider a cleaner pull request with a version switch and tidied up code… It isn't a cleanly written patch, just a quick one for being able to get it running on 3.8.

**Comment by mightymouse2045** [comment]
Ported already
